---
abstract: 'A queueing module with an emphasis on safety, using DBI as a'
author:
  - 'Guillaume Aubert <aubertg@cpan.org>'
build_requires:
  Carp: 0
  DBD::SQLite: 0
  DBI: 0
  Data::Dumper: 0
  MIME::Base64: 0
  Storable: 0
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120530'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Queue-DBI
provides:
  Queue::DBI:
    file: lib/Queue/DBI.pm
    version: v1.7.3
  Queue::DBI::Element:
    file: lib/Queue/DBI/Element.pm
    version: v1.7.3
requires:
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=queue-dbi
  homepage: https://metacpan.org/release/Queue-DBI
  license: http://opensource.org/licenses/artistic-license.php
  repository: https://sourceforge.net/p/queuedbiperl/code
version: v1.7.3
