---
abstract: "A queueing module with an emphasis on safety, using DBI as a\nstorage system for queued data."
author:
  - 'Guillaume Aubert <aubertg@cpan.org>'
build_requires:
  Carp: 0
  DBD::SQLite: 0
  DBI: 0
  Data::Dumper: 0
  MIME::Base64: 0
  Storable: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Queue-DBI
provides:
  Queue::DBI:
    file: lib/Queue/DBI.pm
    version: v1.7.2
  Queue::DBI::Element:
    file: lib/Queue/DBI/Element.pm
    version: v1.7.2
requires:
  perl: 5.006
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: v1.7.2
